name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: pnpm/action-setup@v2.0.0
        with:
          version: 6.0.1

      - run: pnpm install --frozen-lockfile
      - run: pnpm lint

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: pnpm/action-setup@v2.0.0
        with:
          version: 6.0.1

      - run: pnpm install --frozen-lockfile
      - run: pnpm test
